//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMail.BeidouService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BeidouService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MvcMail.BeidouService.BalanceState GetBalance(int Id, string Name, string Psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcMail.BeidouService.BalanceState> GetBalanceAsync(int Id, string Name, string Psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalanceStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetBalanceStr(int Id, string Name, string Psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalanceStr", ReplyAction="*")]
        System.Threading.Tasks.Task GetBalanceStrAsync(int Id, string Name, string Psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MvcMail.BeidouService.SmsInfo GetSmsInfo(int Id, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcMail.BeidouService.SmsInfo> GetSmsInfoAsync(int Id, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsInfoStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetSmsInfoStr(int Id, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsInfoStr", ReplyAction="*")]
        System.Threading.Tasks.Task GetSmsInfoStrAsync(int Id, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UserLogin(int Id, string Name, string Psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UserLoginAsync(int Id, string Name, string Psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLoginStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UserLoginStr(int Id, string Name, string Psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLoginStr", ReplyAction="*")]
        System.Threading.Tasks.Task UserLoginStrAsync(int Id, string Name, string Psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePsw", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdatePsw(int Id, string Name, string OldPsw, string NewPsw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePsw", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdatePswAsync(int Id, string Name, string OldPsw, string NewPsw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePswStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdatePswStr(int Id, string Name, string OldPsw, string NewPsw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePswStr", ReplyAction="*")]
        System.Threading.Tasks.Task UpdatePswStrAsync(int Id, string Name, string OldPsw, string NewPsw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckKeywords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckKeywords(int Id, string Name, string Psw, string Keywords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckKeywords", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckKeywordsAsync(int Id, string Name, string Psw, string Keywords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckKeywordsStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CheckKeywordsStr(int Id, string Name, string Psw, string Keywords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckKeywordsStr", ReplyAction="*")]
        System.Threading.Tasks.Task CheckKeywordsStrAsync(int Id, string Name, string Psw, string Keywords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MvcMail.BeidouService.SendState SendMessage(int Id, string Name, string Psw, string Message, string Phone, long Timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcMail.BeidouService.SendState> SendMessageAsync(int Id, string Name, string Psw, string Message, string Phone, long Timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SendMessageStr(int Id, string Name, string Psw, string Message, string Phone, long Timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageStr", ReplyAction="*")]
        System.Threading.Tasks.Task SendMessageStrAsync(int Id, string Name, string Psw, string Message, string Phone, long Timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTimer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MvcMail.BeidouService.SendState SendTimer(int Id, string Name, string Psw, string Message, string Phone, string SendTime, long Timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTimer", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcMail.BeidouService.SendState> SendTimerAsync(int Id, string Name, string Psw, string Message, string Phone, string SendTime, long Timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTimerStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SendTimerStr(int Id, string Name, string Psw, string Message, string Phone, string SendTime, long Timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTimerStr", ReplyAction="*")]
        System.Threading.Tasks.Task SendTimerStrAsync(int Id, string Name, string Psw, string Message, string Phone, string SendTime, long Timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageExt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MvcMail.BeidouService.SendState SendMessageExt(int Id, string Name, string Psw, string Message, string Phone, long Timestamp, string Ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageExt", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcMail.BeidouService.SendState> SendMessageExtAsync(int Id, string Name, string Psw, string Message, string Phone, long Timestamp, string Ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageStrExt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SendMessageStrExt(int Id, string Name, string Psw, string Message, string Phone, long Timestamp, string Ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageStrExt", ReplyAction="*")]
        System.Threading.Tasks.Task SendMessageStrExtAsync(int Id, string Name, string Psw, string Message, string Phone, long Timestamp, string Ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSPHM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object GetSPHM(string pSp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSPHM", ReplyAction="*")]
        System.Threading.Tasks.Task<object> GetSPHMAsync(string pSp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSPHMStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetSPHMStr(string pSp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSPHMStr", ReplyAction="*")]
        System.Threading.Tasks.Task GetSPHMStrAsync(string pSp);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BalanceState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int balanceField;
        
        private int sendedField;
        
        private int stateField;
        
        private int totaledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Sended {
            get {
                return this.sendedField;
            }
            set {
                this.sendedField = value;
                this.RaisePropertyChanged("Sended");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Totaled {
            get {
                return this.totaledField;
            }
            set {
                this.totaledField = value;
                this.RaisePropertyChanged("Totaled");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SendState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string failPhoneField;
        
        private int stateField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FailPhone {
            get {
                return this.failPhoneField;
            }
            set {
                this.failPhoneField = value;
                this.RaisePropertyChanged("FailPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SmsInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int smsMaxField;
        
        private int yDSmsLenField;
        
        private int lTSmsLenField;
        
        private int dXSmsLenField;
        
        private int xLTSmsLenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SmsMax {
            get {
                return this.smsMaxField;
            }
            set {
                this.smsMaxField = value;
                this.RaisePropertyChanged("SmsMax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int YDSmsLen {
            get {
                return this.yDSmsLenField;
            }
            set {
                this.yDSmsLenField = value;
                this.RaisePropertyChanged("YDSmsLen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LTSmsLen {
            get {
                return this.lTSmsLenField;
            }
            set {
                this.lTSmsLenField = value;
                this.RaisePropertyChanged("LTSmsLen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int DXSmsLen {
            get {
                return this.dXSmsLenField;
            }
            set {
                this.dXSmsLenField = value;
                this.RaisePropertyChanged("DXSmsLen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int XLTSmsLen {
            get {
                return this.xLTSmsLenField;
            }
            set {
                this.xLTSmsLenField = value;
                this.RaisePropertyChanged("XLTSmsLen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : MvcMail.BeidouService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<MvcMail.BeidouService.ServiceSoap>, MvcMail.BeidouService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MvcMail.BeidouService.BalanceState GetBalance(int Id, string Name, string Psw) {
            return base.Channel.GetBalance(Id, Name, Psw);
        }
        
        public System.Threading.Tasks.Task<MvcMail.BeidouService.BalanceState> GetBalanceAsync(int Id, string Name, string Psw) {
            return base.Channel.GetBalanceAsync(Id, Name, Psw);
        }
        
        public void GetBalanceStr(int Id, string Name, string Psw) {
            base.Channel.GetBalanceStr(Id, Name, Psw);
        }
        
        public System.Threading.Tasks.Task GetBalanceStrAsync(int Id, string Name, string Psw) {
            return base.Channel.GetBalanceStrAsync(Id, Name, Psw);
        }
        
        public MvcMail.BeidouService.SmsInfo GetSmsInfo(int Id, string Name) {
            return base.Channel.GetSmsInfo(Id, Name);
        }
        
        public System.Threading.Tasks.Task<MvcMail.BeidouService.SmsInfo> GetSmsInfoAsync(int Id, string Name) {
            return base.Channel.GetSmsInfoAsync(Id, Name);
        }
        
        public void GetSmsInfoStr(int Id, string Name) {
            base.Channel.GetSmsInfoStr(Id, Name);
        }
        
        public System.Threading.Tasks.Task GetSmsInfoStrAsync(int Id, string Name) {
            return base.Channel.GetSmsInfoStrAsync(Id, Name);
        }
        
        public int UserLogin(int Id, string Name, string Psw) {
            return base.Channel.UserLogin(Id, Name, Psw);
        }
        
        public System.Threading.Tasks.Task<int> UserLoginAsync(int Id, string Name, string Psw) {
            return base.Channel.UserLoginAsync(Id, Name, Psw);
        }
        
        public void UserLoginStr(int Id, string Name, string Psw) {
            base.Channel.UserLoginStr(Id, Name, Psw);
        }
        
        public System.Threading.Tasks.Task UserLoginStrAsync(int Id, string Name, string Psw) {
            return base.Channel.UserLoginStrAsync(Id, Name, Psw);
        }
        
        public int UpdatePsw(int Id, string Name, string OldPsw, string NewPsw) {
            return base.Channel.UpdatePsw(Id, Name, OldPsw, NewPsw);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePswAsync(int Id, string Name, string OldPsw, string NewPsw) {
            return base.Channel.UpdatePswAsync(Id, Name, OldPsw, NewPsw);
        }
        
        public void UpdatePswStr(int Id, string Name, string OldPsw, string NewPsw) {
            base.Channel.UpdatePswStr(Id, Name, OldPsw, NewPsw);
        }
        
        public System.Threading.Tasks.Task UpdatePswStrAsync(int Id, string Name, string OldPsw, string NewPsw) {
            return base.Channel.UpdatePswStrAsync(Id, Name, OldPsw, NewPsw);
        }
        
        public string CheckKeywords(int Id, string Name, string Psw, string Keywords) {
            return base.Channel.CheckKeywords(Id, Name, Psw, Keywords);
        }
        
        public System.Threading.Tasks.Task<string> CheckKeywordsAsync(int Id, string Name, string Psw, string Keywords) {
            return base.Channel.CheckKeywordsAsync(Id, Name, Psw, Keywords);
        }
        
        public void CheckKeywordsStr(int Id, string Name, string Psw, string Keywords) {
            base.Channel.CheckKeywordsStr(Id, Name, Psw, Keywords);
        }
        
        public System.Threading.Tasks.Task CheckKeywordsStrAsync(int Id, string Name, string Psw, string Keywords) {
            return base.Channel.CheckKeywordsStrAsync(Id, Name, Psw, Keywords);
        }
        
        public MvcMail.BeidouService.SendState SendMessage(int Id, string Name, string Psw, string Message, string Phone, long Timestamp) {
            return base.Channel.SendMessage(Id, Name, Psw, Message, Phone, Timestamp);
        }
        
        public System.Threading.Tasks.Task<MvcMail.BeidouService.SendState> SendMessageAsync(int Id, string Name, string Psw, string Message, string Phone, long Timestamp) {
            return base.Channel.SendMessageAsync(Id, Name, Psw, Message, Phone, Timestamp);
        }
        
        public void SendMessageStr(int Id, string Name, string Psw, string Message, string Phone, long Timestamp) {
            base.Channel.SendMessageStr(Id, Name, Psw, Message, Phone, Timestamp);
        }
        
        public System.Threading.Tasks.Task SendMessageStrAsync(int Id, string Name, string Psw, string Message, string Phone, long Timestamp) {
            return base.Channel.SendMessageStrAsync(Id, Name, Psw, Message, Phone, Timestamp);
        }
        
        public MvcMail.BeidouService.SendState SendTimer(int Id, string Name, string Psw, string Message, string Phone, string SendTime, long Timestamp) {
            return base.Channel.SendTimer(Id, Name, Psw, Message, Phone, SendTime, Timestamp);
        }
        
        public System.Threading.Tasks.Task<MvcMail.BeidouService.SendState> SendTimerAsync(int Id, string Name, string Psw, string Message, string Phone, string SendTime, long Timestamp) {
            return base.Channel.SendTimerAsync(Id, Name, Psw, Message, Phone, SendTime, Timestamp);
        }
        
        public void SendTimerStr(int Id, string Name, string Psw, string Message, string Phone, string SendTime, long Timestamp) {
            base.Channel.SendTimerStr(Id, Name, Psw, Message, Phone, SendTime, Timestamp);
        }
        
        public System.Threading.Tasks.Task SendTimerStrAsync(int Id, string Name, string Psw, string Message, string Phone, string SendTime, long Timestamp) {
            return base.Channel.SendTimerStrAsync(Id, Name, Psw, Message, Phone, SendTime, Timestamp);
        }
        
        public MvcMail.BeidouService.SendState SendMessageExt(int Id, string Name, string Psw, string Message, string Phone, long Timestamp, string Ext) {
            return base.Channel.SendMessageExt(Id, Name, Psw, Message, Phone, Timestamp, Ext);
        }
        
        public System.Threading.Tasks.Task<MvcMail.BeidouService.SendState> SendMessageExtAsync(int Id, string Name, string Psw, string Message, string Phone, long Timestamp, string Ext) {
            return base.Channel.SendMessageExtAsync(Id, Name, Psw, Message, Phone, Timestamp, Ext);
        }
        
        public void SendMessageStrExt(int Id, string Name, string Psw, string Message, string Phone, long Timestamp, string Ext) {
            base.Channel.SendMessageStrExt(Id, Name, Psw, Message, Phone, Timestamp, Ext);
        }
        
        public System.Threading.Tasks.Task SendMessageStrExtAsync(int Id, string Name, string Psw, string Message, string Phone, long Timestamp, string Ext) {
            return base.Channel.SendMessageStrExtAsync(Id, Name, Psw, Message, Phone, Timestamp, Ext);
        }
        
        public object GetSPHM(string pSp) {
            return base.Channel.GetSPHM(pSp);
        }
        
        public System.Threading.Tasks.Task<object> GetSPHMAsync(string pSp) {
            return base.Channel.GetSPHMAsync(pSp);
        }
        
        public void GetSPHMStr(string pSp) {
            base.Channel.GetSPHMStr(pSp);
        }
        
        public System.Threading.Tasks.Task GetSPHMStrAsync(string pSp) {
            return base.Channel.GetSPHMStrAsync(pSp);
        }
    }
}
